spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson.date-format: dd/MM/yyyy HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:5432/tcc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
    platform: postgres